//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backstage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing {0}....
        /// </summary>
        internal static string Committing {
            get {
                return ResourceManager.GetString("Committing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context factory is not ready..
        /// </summary>
        internal static string ContextFactoryNotReady {
            get {
                return ResourceManager.GetString("ContextFactoryNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context is not ready..
        /// </summary>
        internal static string ContextNotReady {
            get {
                return ResourceManager.GetString("ContextNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context provider factory {0} returned a null IContextProvider..
        /// </summary>
        internal static string ContextProviderFactoryReturnedNull {
            get {
                return ResourceManager.GetString("ContextProviderFactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing {0}....
        /// </summary>
        internal static string Disposing {
            get {
                return ResourceManager.GetString("Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing async command {0}. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileExecutingCommandAsync {
            get {
                return ResourceManager.GetString("ErrorWhileExecutingCommandAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting {0}. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileStarting {
            get {
                return ResourceManager.GetString("ErrorWhileStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current context holder ({0}) returned no current context..
        /// </summary>
        internal static string NoCurrentContext {
            get {
                return ResourceManager.GetString("NoCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current context factory has been defined. You must call ContextFactory.StartNew..
        /// </summary>
        internal static string NoCurrentContextFactory {
            get {
                return ResourceManager.GetString("NoCurrentContextFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started in {1} milliseconds..
        /// </summary>
        internal static string StartedIn {
            get {
                return ResourceManager.GetString("StartedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction options cannot be modified when there is a dependent transaction..
        /// </summary>
        internal static string TransactionOptionsCannotBeModified {
            get {
                return ResourceManager.GetString("TransactionOptionsCannotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set a new current context because there is already a current context that is ready. You must first commit / dispose the current context..
        /// </summary>
        internal static string UnableToSetCurrentContextBecauseThereIsAlreadyOne {
            get {
                return ResourceManager.GetString("UnableToSetCurrentContextBecauseThereIsAlreadyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0}..
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
    }
}
