//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backstage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0}..
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} committed in {1} milliseconds..
        /// </summary>
        internal static string CommittedIn {
            get {
                return ResourceManager.GetString("CommittedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing {0}....
        /// </summary>
        internal static string Committing {
            get {
                return ResourceManager.GetString("Committing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context factory is not ready..
        /// </summary>
        internal static string ContextFactoryNotReady {
            get {
                return ResourceManager.GetString("ContextFactoryNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context is not ready..
        /// </summary>
        internal static string ContextNotReady {
            get {
                return ResourceManager.GetString("ContextNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context provider factory {0} returned a null IContextProvider..
        /// </summary>
        internal static string ContextProviderFactoryReturnedNull {
            get {
                return ResourceManager.GetString("ContextProviderFactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine property name from {0}..
        /// </summary>
        internal static string CouldNotDeterminePropertyName {
            get {
                return ResourceManager.GetString("CouldNotDeterminePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing {0}....
        /// </summary>
        internal static string Disposing {
            get {
                return ResourceManager.GetString("Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain events handlers should implement IHandleDomainEvent. Actual type: {0}..
        /// </summary>
        internal static string DomainHandlersShouldImplementIHandleDomainEvent {
            get {
                return ResourceManager.GetString("DomainHandlersShouldImplementIHandleDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while committing transaction. See inner exception for more information..
        /// </summary>
        internal static string ErrorWhileCommitting {
            get {
                return ResourceManager.GetString("ErrorWhileCommitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while creating type {0}. Please check that there is a default constructor. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileCreatingTypeDefaultConstructor {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingTypeDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing async command {0}. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileExecutingCommandAsync {
            get {
                return ResourceManager.GetString("ErrorWhileExecutingCommandAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while raising domain event {0} with handler {1}. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileRaisingDomainEvent {
            get {
                return ResourceManager.GetString("ErrorWhileRaisingDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while scanning assembly {0}. LoaderExceptions: {1}..
        /// </summary>
        internal static string ErrorWhileScanningAssembly {
            get {
                return ResourceManager.GetString("ErrorWhileScanningAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting {0}. See inner exception for more details..
        /// </summary>
        internal static string ErrorWhileStarting {
            get {
                return ResourceManager.GetString("ErrorWhileStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event {0} raised..
        /// </summary>
        internal static string EventRaised {
            get {
                return ResourceManager.GetString("EventRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed {0}..
        /// </summary>
        internal static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed async {0}..
        /// </summary>
        internal static string ExecutedAsync {
            get {
                return ResourceManager.GetString("ExecutedAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed async {0} -&gt; {1}..
        /// </summary>
        internal static string ExecutedAsyncWithResult {
            get {
                return ResourceManager.GetString("ExecutedAsyncWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed {0} -&gt; {1}..
        /// </summary>
        internal static string ExecutedWithResult {
            get {
                return ResourceManager.GetString("ExecutedWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfilled {0} -&gt; {1}..
        /// </summary>
        internal static string Fulfilled {
            get {
                return ResourceManager.GetString("Fulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GotById {0}, {1} -&gt; {2}..
        /// </summary>
        internal static string GotById {
            get {
                return ResourceManager.GetString("GotById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not an enum..
        /// </summary>
        internal static string MustBeEnum {
            get {
                return ResourceManager.GetString("MustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current context holder ({0}) returned no current context..
        /// </summary>
        internal static string NoCurrentContext {
            get {
                return ResourceManager.GetString("NoCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current context factory has been defined. You must call ContextFactory.StartNew..
        /// </summary>
        internal static string NoCurrentContextFactory {
            get {
                return ResourceManager.GetString("NoCurrentContextFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising event {0}....
        /// </summary>
        internal static string RaisingEvent {
            get {
                return ResourceManager.GetString("RaisingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloaded {0}..
        /// </summary>
        internal static string Reloaded {
            get {
                return ResourceManager.GetString("Reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0}..
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned assemblies and found {0} blueprints..
        /// </summary>
        internal static string ScannedAndFoundBlueprints {
            get {
                return ResourceManager.GetString("ScannedAndFoundBlueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned {0} and found {1} event handlers..
        /// </summary>
        internal static string ScannedAndFoundDomainEventHandlers {
            get {
                return ResourceManager.GetString("ScannedAndFoundDomainEventHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning assemblies for blueprints....
        /// </summary>
        internal static string ScanningAssembliesForBlueprints {
            get {
                return ResourceManager.GetString("ScanningAssembliesForBlueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security provider {0} returned no result for operation {1}. Assuming a false, but you should have a look..
        /// </summary>
        internal static string SecurityProviderReturnedNoResult {
            get {
                return ResourceManager.GetString("SecurityProviderReturnedNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security provider {0} returned no result for operation {1} and target {2}. Assuming a false, but you should have a look..
        /// </summary>
        internal static string SecurityProviderReturnedNoResultWithTarget {
            get {
                return ResourceManager.GetString("SecurityProviderReturnedNoResultWithTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security provider {0} returned no result for operation {1}, target {2} and field {3}. Assuming a false, but you should have a look..
        /// </summary>
        internal static string SecurityProviderReturnedNoResultWithTargetAndField {
            get {
                return ResourceManager.GetString("SecurityProviderReturnedNoResultWithTargetAndField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection function of the composite provider factory returned an empty IContextProvider for {0}..
        /// </summary>
        internal static string SelectionFunctionReturnedNull {
            get {
                return ResourceManager.GetString("SelectionFunctionReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started async execution of {0}..
        /// </summary>
        internal static string StartedAsyncExecution {
            get {
                return ResourceManager.GetString("StartedAsyncExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started in {1} milliseconds..
        /// </summary>
        internal static string StartedIn {
            get {
                return ResourceManager.GetString("StartedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction options cannot be modified when there is a dependent transaction..
        /// </summary>
        internal static string TransactionOptionsCannotBeModified {
            get {
                return ResourceManager.GetString("TransactionOptionsCannotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement the IEntity interface to be able to add it to the current context..
        /// </summary>
        internal static string TypeMustBeIEntity {
            get {
                return ResourceManager.GetString("TypeMustBeIEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a blueprint for {0}. Please verify that there is an implementation of IBlueprint&lt;{0}&gt; and that it is accessible by the current AppDomain..
        /// </summary>
        internal static string UnableToFindABlueprint {
            get {
                return ResourceManager.GetString("UnableToFindABlueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set a new current context because there is already a current context that is ready. You must first commit / dispose the current context..
        /// </summary>
        internal static string UnableToSetCurrentContextBecauseThereIsAlreadyOne {
            get {
                return ResourceManager.GetString("UnableToSetCurrentContextBecauseThereIsAlreadyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0}..
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No security provider has been specified. All operations are authorized..
        /// </summary>
        internal static string UsingDefaultNoSecurityProvider {
            get {
                return ResourceManager.GetString("UsingDefaultNoSecurityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} implements the non-generic variant of IBlueprint. Please use the generic IBlueprint&lt;T&gt;..
        /// </summary>
        internal static string UsingNonGenericIBlueprint {
            get {
                return ResourceManager.GetString("UsingNonGenericIBlueprint", resourceCulture);
            }
        }
    }
}
